In [1]:
import numpy as np

Exercice 1 : Create a 1D NumPy array containing numbers from 0 to 9.

In [2]:
np_array = np.arange(10)
print(np_array)

[0 1 2 3 4 5 6 7 8 9]


Exercice 2

In [ ]:
list_number = [3.14, 2.17, 0, 1, 2] 
np_number_int = np.array(list_number, dtype=int)
print(np_number_int)

[3 2 0 1 2]


Exercice 3

In [5]:
np_shape_3x3 = np.arange(1, 10).reshape(3,3)
print(np_shape_3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Exercice 4

In [12]:
np_random = np.round(np.random.rand(4, 5), 2)
print(np_random)

[[0.78 0.07 0.15 0.11 0.71]
 [0.93 0.99 0.48 0.36 0.56]
 [0.99 0.64 0.82 0.44 0.8 ]
 [0.82 0.19 0.21 0.87 0.41]]


Exercice 5

In [13]:
array = np.array([
    [21,22,23,22,22],
    [20, 21, 22, 23, 24],
    [21,22,23,22,22]
    ])

second_row = array[1]
print(second_row)

[20 21 22 23 24]


Exercice 6

In [14]:
#De l'exercice 1
np_array_reverse = np_array[::-1]
print(np_array_reverse)

[9 8 7 6 5 4 3 2 1 0]


Exercice 7

In [ ]:
np_identity = np.eye(4)
print(np_identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Exercice 8

In [16]:
#A partir de l'exercice 6
print(f"Sum: {np_array_reverse.sum()}, Average: {np_array_reverse.mean()}")

Sum: 45, Average: 4.5


Exercice 9

In [18]:
np_shape_4x5 = np.arange(1, 21).reshape(4,5)
print(np_shape_4x5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Exercice 10

In [21]:
np_odd = np_array[1::2]
print(np_odd)
# Par contre on va éviter le dessus en faisant une vrai vérification
np_odd = np_array[np_array % 2 == 1]
print(np_odd)


[1 3 5 7 9]
[1 3 5 7 9]
